/**
 * Fallback sample data used when Supabase is not configured.
 * This lets the site render with realistic-looking content for development / demo.
 *
 * Cover images are sourced from Open Library (covers.openlibrary.org) which
 * provides free, hotlinkable book cover images.
 */

export const sampleAuthors = [
	{
		id: 1,
		name: {
			en: "Ibn Taymiyyah",
			ar: "ابن تيمية",
			ur: "ابن تیمیہ",
			bn: "ইবনে তাইমিয়া",
		},
		birth_year: 661,
		death_year: 728,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 2,
		name: {
			en: "Ibn al-Qayyim",
			ar: "ابن القيم",
			ur: "ابن القیم",
			bn: "ইবনুল কায়্যিম",
		},
		birth_year: 691,
		death_year: 751,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 3,
		name: {
			en: "Imam an-Nawawi",
			ar: "الإمام النووي",
			ur: "امام نووی",
			bn: "ইমাম নববী",
		},
		birth_year: 631,
		death_year: 676,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 4,
		name: {
			en: "Shaykh Ibn Baz",
			ar: "الشيخ ابن باز",
			ur: "شیخ ابن باز",
			bn: "শাইখ ইবনে বায",
		},
		birth_year: 1330,
		death_year: 1420,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 5,
		name: {
			en: "Shaykh al-Uthaymeen",
			ar: "الشيخ العثيمين",
			ur: "شیخ عثیمین",
			bn: "শাইখ উসাইমীন",
		},
		birth_year: 1347,
		death_year: 1421,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 6,
		name: {
			en: "Shaykh al-Albani",
			ar: "الشيخ الألباني",
			ur: "شیخ البانی",
			bn: "শাইখ আলবানী",
		},
		birth_year: 1333,
		death_year: 1420,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 7,
		name: {
			en: "Ibn Kathir",
			ar: "ابن كثير",
			ur: "ابن کثیر",
			bn: "ইবনে কাসীর",
		},
		birth_year: 700,
		death_year: 774,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 8,
		name: {
			en: "Imam al-Bukhari",
			ar: "الإمام البخاري",
			ur: "امام بخاری",
			bn: "ইমাম বুখারী",
		},
		birth_year: 194,
		death_year: 256,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 9,
		name: {
			en: "Muhammad ibn Abdul-Wahhab",
			ar: "محمد بن عبد الوهاب",
			ur: "محمد بن عبدالوہاب",
			bn: "মুহাম্মাদ ইবনে আব্দুল ওয়াহহাব",
		},
		birth_year: 1115,
		death_year: 1206,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 10,
		name: {
			en: "Imam Muslim",
			ar: "الإمام مسلم",
			ur: "امام مسلم",
			bn: "ইমাম মুসলিম",
		},
		birth_year: 206,
		death_year: 261,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 11,
		name: {
			en: "Ibn Hajar al-Asqalani",
			ar: "ابن حجر العسقلاني",
			ur: "ابن حجر عسقلانی",
			bn: "ইবনে হাজার আসকালানী",
		},
		birth_year: 773,
		death_year: 852,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
	{
		id: 12,
		name: {
			en: "Imam al-Ghazali",
			ar: "الإمام الغزالي",
			ur: "امام غزالی",
			bn: "ইমাম গাযালী",
		},
		birth_year: 450,
		death_year: 505,
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
	},
];

// ── Helper to build an Open Library cover URL from an ISBN ──────────────────
const olCover = (isbn: string, size: "S" | "M" | "L" = "L") =>
	`https://covers.openlibrary.org/b/isbn/${isbn}-${size}.jpg`;

export const sampleBooks = [
	// ────────────────────────── AQEEDAH ──────────────────────────
	{
		id: 1,
		title: { en: "Kitab at-Tawheed", ar: "كتاب التوحيد" },
		slug: "kitab-at-tawheed",
		author_id: 9,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "A foundational text on Islamic monotheism explaining the true meaning of Tawheed and its categories. Written by Muhammad ibn Abdul-Wahhab, it is widely studied across the Muslim world.",
			ar: "كتاب أساسي في التوحيد الإسلامي يشرح معنى التوحيد وأقسامه",
		},
		pdf_url: "",
		cover_image_url: olCover("9960740056"),
		page_count: 320,
		is_downloadable: true,
		is_featured: true,
		view_count: 15420,
		download_count: 8930,
		published_at: "2024-01-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 9,
			name: { en: "Muhammad ibn Abdul-Wahhab", ar: "محمد بن عبد الوهاب" },
		},
	},
	{
		id: 2,
		title: { en: "Al-Aqeedah Al-Wasitiyyah", ar: "العقيدة الواسطية" },
		slug: "al-aqeedah-al-wasitiyyah",
		author_id: 1,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "A classic text on the creed of Ahl as-Sunnah wal-Jama'ah, covering the names and attributes of Allah. It is one of Ibn Taymiyyah's most studied works.",
			ar: "رسالة في عقيدة أهل السنة والجماعة",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 96,
		is_downloadable: true,
		is_featured: true,
		view_count: 12800,
		download_count: 6540,
		published_at: "2024-01-20T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 1, name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
	},
	{
		id: 11,
		title: { en: "The Three Fundamental Principles", ar: "الأصول الثلاثة" },
		slug: "three-fundamental-principles",
		author_id: 5,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "An explanation of the three questions asked in the grave: Who is your Lord, your religion, and your Prophet? A must-read for every Muslim.",
			ar: "شرح ثلاثة الأصول",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 80,
		is_downloadable: true,
		is_featured: true,
		view_count: 8900,
		download_count: 5600,
		published_at: "2024-05-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 5,
			name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" },
		},
	},
	{
		id: 15,
		title: {
			en: "Sharh al-Aqeedah at-Tahawiyyah",
			ar: "شرح العقيدة الطحاوية",
		},
		slug: "sharh-al-aqeedah-at-tahawiyyah",
		author_id: 2,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "Commentary on the creed of Imam at-Tahawi, a widely studied text on orthodox Sunni beliefs covering the fundamentals of Islamic theology.",
			ar: "شرح العقيدة الطحاوية",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 540,
		is_downloadable: true,
		is_featured: false,
		view_count: 6100,
		download_count: 3200,
		published_at: "2024-07-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 2, name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
	},
	{
		id: 16,
		title: { en: "Talbis Iblis", ar: "تلبيس إبليس" },
		slug: "talbis-iblis",
		author_id: 2,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "Devil's Deceptions — an exposition of the tricks and schemes of Shaytan upon the children of Adam, refuting deviant sects and innovations.",
			ar: "تلبيس إبليس",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 380,
		is_downloadable: true,
		is_featured: false,
		view_count: 4200,
		download_count: 2100,
		published_at: "2024-07-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 2, name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
	},
	{
		id: 17,
		title: {
			en: "Iqtida as-Sirat al-Mustaqim",
			ar: "اقتضاء الصراط المستقيم",
		},
		slug: "iqtida-as-sirat-al-mustaqim",
		author_id: 1,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "The Requirements of the Straight Path — Ibn Taymiyyah warns against imitating non-Muslims in customs and worship, calling Muslims back to the pure Sunnah.",
			ar: "اقتضاء الصراط المستقيم لمخالفة أصحاب الجحيم",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 340,
		is_downloadable: true,
		is_featured: false,
		view_count: 3800,
		download_count: 1900,
		published_at: "2024-08-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 1, name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
	},
	{
		id: 28,
		title: { en: "Usool as-Sunnah", ar: "أصول السنة" },
		slug: "usool-as-sunnah",
		author_id: 4,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "Foundations of the Sunnah — a concise treatise explaining the fundamental principles of Ahl as-Sunnah wal-Jama'ah regarding creed and methodology.",
			ar: "أصول السنة للإمام أحمد بن حنبل",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 60,
		is_downloadable: true,
		is_featured: false,
		view_count: 3100,
		download_count: 1700,
		published_at: "2024-09-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 4,
			name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" },
		},
	},
	{
		id: 9,
		title: { en: "Madarij as-Salikin", ar: "مدارج السالكين" },
		slug: "madarij-as-salikin",
		author_id: 2,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "Stations of the Seekers — an in-depth exploration of the spiritual stations on the path to Allah, based on the work of al-Harawi.",
			ar: "مدارج السالكين بين منازل إياك نعبد وإياك نستعين",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 900,
		is_downloadable: true,
		is_featured: false,
		view_count: 7600,
		download_count: 4100,
		published_at: "2024-04-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 2, name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
	},
	{
		id: 26,
		title: { en: "Al-Jawab al-Kafi", ar: "الجواب الكافي" },
		slug: "al-jawab-al-kafi",
		author_id: 2,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "The Sufficient Answer — Ibn al-Qayyim answers a question about the cure for sins and disobedience, with deep insights into the heart's ailments and their remedies.",
			ar: "الجواب الكافي لمن سأل عن الدواء الشافي — الداء والدواء",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 320,
		is_downloadable: true,
		is_featured: false,
		view_count: 6800,
		download_count: 3700,
		published_at: "2024-12-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 2, name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
	},
	{
		id: 27,
		title: { en: "Ihya Ulum al-Din", ar: "إحياء علوم الدين" },
		slug: "ihya-ulum-al-din",
		author_id: 12,
		category_id: "aqeedah",
		language_code: "ar",
		description: {
			en: "Revival of the Religious Sciences — Imam al-Ghazali's magnum opus covering worship, daily life, vices, and virtues in extraordinary depth.",
			ar: "إحياء علوم الدين — كتاب الإمام الغزالي",
		},
		pdf_url: "",
		cover_image_url: olCover("9781941610213"),
		page_count: 4400,
		is_downloadable: true,
		is_featured: false,
		view_count: 11200,
		download_count: 6300,
		published_at: "2024-12-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 12,
			name: { en: "Imam al-Ghazali", ar: "الإمام الغزالي" },
		},
	},

	// ────────────────────────── FIQH ──────────────────────────
	{
		id: 12,
		title: { en: "Bulugh al-Maram", ar: "بلوغ المرام" },
		slug: "bulugh-al-maram",
		author_id: 11,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "A collection of hadith pertaining to Islamic jurisprudence compiled by Ibn Hajar al-Asqalani. It is widely used as a primary reference for deriving fiqh rulings.",
			ar: "بلوغ المرام من أدلة الأحكام",
		},
		pdf_url: "",
		cover_image_url: olCover("9786035000826"),
		page_count: 450,
		is_downloadable: true,
		is_featured: false,
		view_count: 6700,
		download_count: 3400,
		published_at: "2024-05-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 11,
			name: { en: "Ibn Hajar al-Asqalani", ar: "ابن حجر العسقلاني" },
		},
	},
	{
		id: 18,
		title: { en: "Al-Sharh al-Mumti'", ar: "الشرح الممتع" },
		slug: "al-sharh-al-mumti",
		author_id: 5,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "The Enjoyable Explanation — Shaykh al-Uthaymeen's comprehensive commentary on Zad al-Mustaqni', covering Hanbali fiqh in detail.",
			ar: "الشرح الممتع على زاد المستقنع",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 3600,
		is_downloadable: true,
		is_featured: false,
		view_count: 7800,
		download_count: 4200,
		published_at: "2024-08-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 5,
			name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" },
		},
	},
	{
		id: 29,
		title: { en: "Minhaj at-Talibin", ar: "منهاج الطالبين" },
		slug: "minhaj-at-talibin",
		author_id: 3,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "The Way of the Seekers — Imam an-Nawawi's authoritative work on Shafi'i fiqh, covering worship, transactions, marriage, and more.",
			ar: "منهاج الطالبين وعمدة المفتين",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 520,
		is_downloadable: true,
		is_featured: false,
		view_count: 5400,
		download_count: 2800,
		published_at: "2024-09-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 3,
			name: { en: "Imam an-Nawawi", ar: "الإمام النووي" },
		},
	},
	{
		id: 8,
		title: { en: "Majmu' al-Fatawa", ar: "مجموع الفتاوى" },
		slug: "majmu-al-fatawa",
		author_id: 1,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "A comprehensive 37-volume collection of religious rulings and answers by Shaykh al-Islam Ibn Taymiyyah, covering creed, worship, and more.",
			ar: "مجموع فتاوى شيخ الإسلام ابن تيمية",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 5400,
		is_downloadable: true,
		is_featured: false,
		view_count: 9800,
		download_count: 5200,
		published_at: "2024-03-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 1, name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
	},
	{
		id: 25,
		title: { en: "Fatawa Ibn Baz", ar: "فتاوى ابن باز" },
		slug: "fatawa-ibn-baz",
		author_id: 4,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "A multi-volume compilation of fatawa (religious rulings) by Shaykh Ibn Baz on topics of creed, worship, transactions, and contemporary issues.",
			ar: "مجموع فتاوى ومقالات الشيخ ابن باز",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 4200,
		is_downloadable: true,
		is_featured: false,
		view_count: 7300,
		download_count: 4100,
		published_at: "2024-11-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 4,
			name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" },
		},
	},
	{
		id: 34,
		title: {
			en: "Fatawa al-Lajnah ad-Da'imah",
			ar: "فتاوى اللجنة الدائمة",
		},
		slug: "fatawa-al-lajnah",
		author_id: 4,
		category_id: "fiqh",
		language_code: "ar",
		description: {
			en: "A compilation of fatawa issued by the Permanent Committee for Scholarly Research and Ifta of Saudi Arabia, covering all aspects of Islamic life.",
			ar: "فتاوى اللجنة الدائمة للبحوث العلمية والإفتاء",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 3200,
		is_downloadable: true,
		is_featured: false,
		view_count: 5200,
		download_count: 2800,
		published_at: "2024-12-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 4,
			name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" },
		},
	},

	// ────────────────────────── HADITH ──────────────────────────
	{
		id: 4,
		title: { en: "Riyad as-Salihin", ar: "رياض الصالحين" },
		slug: "riyad-as-salihin",
		author_id: 3,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "Gardens of the Righteous — a compilation of hadith covering all aspects of a Muslim's daily life, from worship to manners to governance.",
			ar: "رياض الصالحين من كلام سيد المرسلين",
		},
		pdf_url: "",
		cover_image_url: olCover("9781590080160"),
		page_count: 680,
		is_downloadable: true,
		is_featured: true,
		view_count: 22500,
		download_count: 14300,
		published_at: "2024-02-10T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 3,
			name: { en: "Imam an-Nawawi", ar: "الإمام النووي" },
		},
	},
	{
		id: 5,
		title: { en: "Al-Arba'in An-Nawawiyyah", ar: "الأربعين النووية" },
		slug: "al-arbain-an-nawawiyyah",
		author_id: 3,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "The Forty Hadith of Imam Nawawi — a concise collection of 42 fundamental prophetic traditions that form the core of Islamic teachings.",
			ar: "الأربعون حديثاً النووية",
		},
		pdf_url: "",
		cover_image_url: olCover("9780946621651"),
		page_count: 120,
		is_downloadable: true,
		is_featured: true,
		view_count: 31200,
		download_count: 19800,
		published_at: "2024-02-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 3,
			name: { en: "Imam an-Nawawi", ar: "الإمام النووي" },
		},
	},
	{
		id: 7,
		title: { en: "Sahih al-Bukhari", ar: "صحيح البخاري" },
		slug: "sahih-al-bukhari",
		author_id: 8,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "The most authentic collection of hadith, compiled by Imam al-Bukhari over 16 years from over 600,000 narrations. It contains 7,563 hadith.",
			ar: "الجامع المسند الصحيح المختصر من أمور رسول الله ﷺ وسننه وأيامه",
		},
		pdf_url: "",
		cover_image_url: olCover("9781567445190"),
		page_count: 2600,
		is_downloadable: true,
		is_featured: true,
		view_count: 45200,
		download_count: 29400,
		published_at: "2024-03-10T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 8,
			name: { en: "Imam al-Bukhari", ar: "الإمام البخاري" },
		},
	},
	{
		id: 10,
		title: { en: "Fath al-Bari", ar: "فتح الباري" },
		slug: "fath-al-bari",
		author_id: 11,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "The most celebrated commentary on Sahih al-Bukhari, authored by Ibn Hajar al-Asqalani. It took him 25 years to complete.",
			ar: "فتح الباري شرح صحيح البخاري",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 4800,
		is_downloadable: true,
		is_featured: false,
		view_count: 11300,
		download_count: 6800,
		published_at: "2024-04-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 11,
			name: { en: "Ibn Hajar al-Asqalani", ar: "ابن حجر العسقلاني" },
		},
	},
	{
		id: 13,
		title: {
			en: "Silsilat al-Ahadith as-Sahihah",
			ar: "سلسلة الأحاديث الصحيحة",
		},
		slug: "silsilat-al-ahadith-as-sahihah",
		author_id: 6,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "Series of Authentic Hadith — a multi-volume verification and compilation of authentic hadith by the master of modern hadith science.",
			ar: "سلسلة الأحاديث الصحيحة وشيء من فقهها وفوائدها",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 2100,
		is_downloadable: true,
		is_featured: false,
		view_count: 5400,
		download_count: 2900,
		published_at: "2024-06-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 6,
			name: { en: "Shaykh al-Albani", ar: "الشيخ الألباني" },
		},
	},
	{
		id: 19,
		title: { en: "Sahih Muslim", ar: "صحيح مسلم" },
		slug: "sahih-muslim",
		author_id: 10,
		category_id: "hadith",
		language_code: "ar",
		description: {
			en: "The second most authentic hadith collection after Sahih al-Bukhari, compiled by Imam Muslim. It is known for its strict methodology.",
			ar: "المسند الصحيح المختصر بنقل العدل عن العدل إلى رسول الله ﷺ",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 2200,
		is_downloadable: true,
		is_featured: true,
		view_count: 38400,
		download_count: 24100,
		published_at: "2024-09-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 10, name: { en: "Imam Muslim", ar: "الإمام مسلم" } },
	},

	// ────────────────────────── TAFSEER ──────────────────────────
	{
		id: 6,
		title: { en: "Tafsir Ibn Kathir", ar: "تفسير ابن كثير" },
		slug: "tafsir-ibn-kathir",
		author_id: 7,
		category_id: "tafseer",
		language_code: "ar",
		description: {
			en: "One of the most respected tafsirs of the Quran, known for interpreting the Quran using hadith and statements of the Sahabah.",
			ar: "تفسير القرآن العظيم",
		},
		pdf_url: "",
		cover_image_url: olCover("9789960892740"),
		page_count: 3200,
		is_downloadable: true,
		is_featured: true,
		view_count: 28700,
		download_count: 16500,
		published_at: "2024-03-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 7, name: { en: "Ibn Kathir", ar: "ابن كثير" } },
	},
	{
		id: 20,
		title: { en: "Tafsir as-Sa'di", ar: "تفسير السعدي" },
		slug: "tafsir-as-sadi",
		author_id: 5,
		category_id: "tafseer",
		language_code: "ar",
		description: {
			en: "Taysir al-Karim ar-Rahman — A clear and accessible Quranic commentary by Shaykh Abdur-Rahman as-Sa'di, widely recommended for students of knowledge.",
			ar: "تيسير الكريم الرحمن في تفسير كلام المنان",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 1400,
		is_downloadable: true,
		is_featured: false,
		view_count: 9200,
		download_count: 5100,
		published_at: "2024-09-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 5,
			name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" },
		},
	},
	{
		id: 30,
		title: { en: "Tafsir al-Jalalayn", ar: "تفسير الجلالين" },
		slug: "tafsir-al-jalalayn",
		author_id: 3,
		category_id: "tafseer",
		language_code: "ar",
		description: {
			en: "A concise and popular tafsir co-authored by Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti. Known for its brevity and clarity.",
			ar: "تفسير الجلالين — تفسير مختصر للقرآن الكريم",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 800,
		is_downloadable: true,
		is_featured: false,
		view_count: 7300,
		download_count: 3900,
		published_at: "2024-10-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 3,
			name: { en: "Imam an-Nawawi", ar: "الإمام النووي" },
		},
	},

	// ────────────────────────── SEERAH ──────────────────────────
	{
		id: 3,
		title: { en: "Zad al-Ma'ad", ar: "زاد المعاد" },
		slug: "zad-al-maad",
		author_id: 2,
		category_id: "seerah",
		language_code: "ar",
		description: {
			en: "Provisions of the Hereafter — a comprehensive guide to the Prophet's ﷺ life, practices, jurisprudence, and daily routines.",
			ar: "زاد المعاد في هدي خير العباد",
		},
		pdf_url: "",
		cover_image_url: olCover("9781891229237"),
		page_count: 1200,
		is_downloadable: true,
		is_featured: true,
		view_count: 18900,
		download_count: 11200,
		published_at: "2024-02-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 2, name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
	},
	{
		id: 21,
		title: {
			en: "Ar-Raheeq al-Makhtum (The Sealed Nectar)",
			ar: "الرحيق المختوم",
		},
		slug: "ar-raheeq-al-makhtum",
		author_id: 4,
		category_id: "seerah",
		language_code: "ar",
		description: {
			en: "The Sealed Nectar — an award-winning biography of Prophet Muhammad ﷺ by Safi-ur-Rahman Mubarakpuri. Winner of the first prize in a worldwide competition.",
			ar: "الرحيق المختوم — سيرة نبوية",
		},
		pdf_url: "",
		cover_image_url: olCover("9781591440710"),
		page_count: 480,
		is_downloadable: true,
		is_featured: true,
		view_count: 35600,
		download_count: 22800,
		published_at: "2024-10-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 4,
			name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" },
		},
	},
	{
		id: 31,
		title: { en: "As-Seerah An-Nabawiyyah", ar: "السيرة النبوية" },
		slug: "as-seerah-an-nabawiyyah",
		author_id: 7,
		category_id: "seerah",
		language_code: "ar",
		description: {
			en: "The Prophetic Biography as narrated by Ibn Kathir — drawn from his larger work Al-Bidayah wan-Nihayah, focusing on the life of the Prophet ﷺ.",
			ar: "السيرة النبوية لابن كثير",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 960,
		is_downloadable: true,
		is_featured: false,
		view_count: 6800,
		download_count: 3600,
		published_at: "2024-10-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 7, name: { en: "Ibn Kathir", ar: "ابن كثير" } },
	},

	// ────────────────────────── ARABIC LANGUAGE ──────────────────────────
	{
		id: 22,
		title: { en: "Al-Ajrumiyyah", ar: "الآجرومية" },
		slug: "al-ajrumiyyah",
		author_id: 5,
		category_id: "arabic-language",
		language_code: "ar",
		description: {
			en: "A classical primer on Arabic grammar by Ibn Ajurrum, widely used as the first textbook for students of Arabic grammar worldwide.",
			ar: "المقدمة الآجرومية في مبادئ علم العربية",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 40,
		is_downloadable: true,
		is_featured: false,
		view_count: 12400,
		download_count: 8100,
		published_at: "2024-10-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 5,
			name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" },
		},
	},
	{
		id: 23,
		title: { en: "Qatr an-Nada", ar: "قطر الندى" },
		slug: "qatr-an-nada",
		author_id: 1,
		category_id: "arabic-language",
		language_code: "ar",
		description: {
			en: "Drops of Dew — an intermediate Arabic grammar text by Ibn Hisham, covering syntax (nahw) in a clear and structured manner.",
			ar: "قطر الندى وبل الصدى — في النحو العربي",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 180,
		is_downloadable: true,
		is_featured: false,
		view_count: 5600,
		download_count: 3200,
		published_at: "2024-11-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 1, name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
	},
	{
		id: 32,
		title: { en: "Alfiyyat Ibn Malik", ar: "ألفية ابن مالك" },
		slug: "alfiyyat-ibn-malik",
		author_id: 3,
		category_id: "arabic-language",
		language_code: "ar",
		description: {
			en: "The Thousand-Line Poem of Ibn Malik — the most famous didactic poem on Arabic grammar, memorized by students of Arabic worldwide for centuries.",
			ar: "ألفية ابن مالك في النحو والصرف",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 120,
		is_downloadable: true,
		is_featured: false,
		view_count: 8900,
		download_count: 5400,
		published_at: "2024-11-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 3,
			name: { en: "Imam an-Nawawi", ar: "الإمام النووي" },
		},
	},

	// ────────────────────────── HISTORY ──────────────────────────
	{
		id: 14,
		title: { en: "Al-Bidayah wan-Nihayah", ar: "البداية والنهاية" },
		slug: "al-bidayah-wan-nihayah",
		author_id: 7,
		category_id: "history",
		language_code: "ar",
		description: {
			en: "The Beginning and The End — a monumental universal history from the creation of the world through the events of the author's time, by Ibn Kathir.",
			ar: "البداية والنهاية في التاريخ",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 4200,
		is_downloadable: true,
		is_featured: false,
		view_count: 8200,
		download_count: 4700,
		published_at: "2024-06-15T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 7, name: { en: "Ibn Kathir", ar: "ابن كثير" } },
	},
	{
		id: 24,
		title: { en: "Stories of the Prophets", ar: "قصص الأنبياء" },
		slug: "stories-of-the-prophets",
		author_id: 7,
		category_id: "history",
		language_code: "ar",
		description: {
			en: "Qisas al-Anbiya — a collection of stories of the Prophets mentioned in the Quran, narrated by Ibn Kathir with hadith references.",
			ar: "قصص الأنبياء لابن كثير",
		},
		pdf_url: "",
		cover_image_url: olCover("9781591440116"),
		page_count: 460,
		is_downloadable: true,
		is_featured: false,
		view_count: 14600,
		download_count: 9200,
		published_at: "2024-11-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: { id: 7, name: { en: "Ibn Kathir", ar: "ابن كثير" } },
	},
	{
		id: 33,
		title: { en: "Tarikh at-Tabari", ar: "تاريخ الطبري" },
		slug: "tarikh-at-tabari",
		author_id: 8,
		category_id: "history",
		language_code: "ar",
		description: {
			en: "The History of the Prophets and Kings — one of the most comprehensive chronicles of Islamic and pre-Islamic history by Imam at-Tabari.",
			ar: "تاريخ الرسل والملوك — تاريخ الطبري",
		},
		pdf_url: "",
		cover_image_url: null,
		page_count: 5600,
		is_downloadable: true,
		is_featured: false,
		view_count: 4800,
		download_count: 2500,
		published_at: "2024-12-01T00:00:00Z",
		created_at: "2024-01-01T00:00:00Z",
		updated_at: "2024-01-01T00:00:00Z",
		author: {
			id: 8,
			name: { en: "Imam al-Bukhari", ar: "الإمام البخاري" },
		},
	},
];

/** Get featured sample books only */
export function getSampleFeaturedBooks() {
	return sampleBooks.filter((b) => b.is_featured);
}

/** Filter sample books by category id (matches categories.json id/slug) */
export function getSampleBooksByCategory(categorySlug: string) {
	return sampleBooks.filter((b) => b.category_id === categorySlug);
}

/** Filter sample books by search query */
export function searchSampleBooks(query: string) {
	const q = query.toLowerCase();
	return sampleBooks.filter(
		(b) =>
			b.title.en?.toLowerCase().includes(q) ||
			b.title.ar?.includes(q) ||
			b.author?.name?.en?.toLowerCase().includes(q) ||
			b.author?.name?.ar?.includes(q) ||
			b.description?.en?.toLowerCase().includes(q)
	);
}
