/**
 * Fallback sample data used when Supabase is not configured.
 * This lets the site render with realistic-looking content for development / demo.
 *
 * Cover images are sourced from Open Library (covers.openlibrary.org) which
 * provides free, hotlinkable book cover images.
 */

export const sampleAuthors = [
  {
    id: "a1",
    name: { en: "Ibn Taymiyyah", ar: "ابن تيمية", ur: "ابن تیمیہ", bn: "ইবনে তাইমিয়া" },
    bio: {
      en: "Taqī ad-Dīn Aḥmad ibn Taymiyyah (1263–1328) was a renowned Islamic scholar, theologian, and prolific writer. He authored hundreds of works on theology, jurisprudence, and spirituality.",
      ar: "تقي الدين أحمد بن تيمية (661–728 هـ) عالم إسلامي ومفتٍ وفقيه حنبلي، من أبرز علماء الإسلام",
    },
    era: "Classical",
    birth_date_hijri: "661 AH",
    death_date_hijri: "728 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a2",
    name: { en: "Ibn al-Qayyim", ar: "ابن القيم", ur: "ابن القیم", bn: "ইবনুল কায়্যিম" },
    bio: {
      en: "Ibn Qayyim al-Jawziyya (1292–1350) was an Islamic jurist, commentator on the Qur'an, and the most famous student of Ibn Taymiyyah. He authored many influential works on Islamic theology and spirituality.",
      ar: "ابن قيم الجوزية (691–751 هـ) عالم إسلامي وفقيه ومحدث، تلميذ ابن تيمية",
    },
    era: "Classical",
    birth_date_hijri: "691 AH",
    death_date_hijri: "751 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a3",
    name: { en: "Imam an-Nawawi", ar: "الإمام النووي", ur: "امام نووی", bn: "ইমাম নববী" },
    bio: {
      en: "Yaḥyā ibn Sharaf al-Nawawī (1233–1277) was an influential Sunni scholar of Fiqh and Hadith, best known for Riyad as-Salihin and the Forty Hadith collection.",
      ar: "يحيى بن شرف النووي (631–676 هـ) عالم حديث وفقه شهير",
    },
    era: "Classical",
    birth_date_hijri: "631 AH",
    death_date_hijri: "676 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a4",
    name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز", ur: "شیخ ابن باز", bn: "শাইখ ইবনে বায" },
    bio: {
      en: "Abd al-Aziz ibn Baz (1910–1999) served as the Grand Mufti of Saudi Arabia and was one of the most senior scholars of the 20th century.",
      ar: "عبد العزيز بن باز (1330–1420 هـ) المفتي العام للمملكة العربية السعودية",
    },
    era: "Contemporary",
    birth_date_hijri: "1330 AH",
    death_date_hijri: "1420 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a5",
    name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين", ur: "شیخ عثیمین", bn: "শাইখ উসাইমীন" },
    bio: {
      en: "Muhammad ibn al-Uthaymeen (1925–2001) was one of the most prominent Islamic scholars of the 20th century, known for his clear explanations of Islamic texts.",
      ar: "محمد بن صالح العثيمين (1347–1421 هـ) عالم إسلامي بارز ومفسر ومعلم",
    },
    era: "Contemporary",
    birth_date_hijri: "1347 AH",
    death_date_hijri: "1421 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a6",
    name: { en: "Shaykh al-Albani", ar: "الشيخ الألباني", ur: "شیخ البانی", bn: "শাইখ আলবানী" },
    bio: {
      en: "Muhammad Nasir-ud-Din al-Albani (1914–1999) was an Albanian Islamic scholar specializing in Hadith science. He authenticated thousands of hadith.",
      ar: "محمد ناصر الدين الألباني (1333–1420 هـ) محدث ألباني شهير",
    },
    era: "Contemporary",
    birth_date_hijri: "1333 AH",
    death_date_hijri: "1420 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a7",
    name: { en: "Ibn Kathir", ar: "ابن كثير", ur: "ابن کثیر", bn: "ইবনে কাসীর" },
    bio: {
      en: "Ismail ibn Kathir (1300–1373) was a highly influential Islamic scholar, historian, and exegete. His Tafsir is one of the most widely used commentaries of the Quran.",
      ar: "إسماعيل بن كثير (700–774 هـ) عالم ومفسر ومؤرخ إسلامي",
    },
    era: "Classical",
    birth_date_hijri: "700 AH",
    death_date_hijri: "774 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a8",
    name: { en: "Imam al-Bukhari", ar: "الإمام البخاري", ur: "امام بخاری", bn: "ইমাম বুখারী" },
    bio: {
      en: "Muhammad al-Bukhari (810–870 CE) was a Persian Islamic scholar. His Sahih al-Bukhari is considered the most authentic collection of hadith.",
      ar: "محمد البخاري (194–256 هـ) صاحب صحيح البخاري، أصح كتب الحديث",
    },
    era: "Classical",
    birth_date_hijri: "194 AH",
    death_date_hijri: "256 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a9",
    name: { en: "Muhammad ibn Abdul-Wahhab", ar: "محمد بن عبد الوهاب", ur: "محمد بن عبدالوہاب", bn: "মুহাম্মাদ ইবনে আব্দুল ওয়াহহাব" },
    bio: {
      en: "Muhammad ibn Abd al-Wahhab (1703–1792) was a reformist scholar who advocated a return to the Quran and Sunnah. He authored Kitab at-Tawhid.",
      ar: "محمد بن عبد الوهاب (1115–1206 هـ) عالم إسلامي ومصلح",
    },
    era: "Classical",
    birth_date_hijri: "1115 AH",
    death_date_hijri: "1206 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a10",
    name: { en: "Imam Muslim", ar: "الإمام مسلم", ur: "امام مسلم", bn: "ইমাম মুসলিম" },
    bio: {
      en: "Muslim ibn al-Hajjaj (815–875 CE) was a scholar of hadith, most renowned for compiling Sahih Muslim, the second most authentic hadith collection.",
      ar: "مسلم بن الحجاج (206–261 هـ) صاحب صحيح مسلم",
    },
    era: "Classical",
    birth_date_hijri: "206 AH",
    death_date_hijri: "261 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a11",
    name: { en: "Ibn Hajar al-Asqalani", ar: "ابن حجر العسقلاني", ur: "ابن حجر عسقلانی", bn: "ইবনে হাজার আসকালানী" },
    bio: {
      en: "Ibn Hajar al-Asqalani (1372–1449) was a medieval Islamic scholar and the author of Fath al-Bari, the most celebrated commentary on Sahih al-Bukhari.",
      ar: "ابن حجر العسقلاني (773–852 هـ) محدث ومؤرخ وفقيه شافعي",
    },
    era: "Classical",
    birth_date_hijri: "773 AH",
    death_date_hijri: "852 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "a12",
    name: { en: "Imam al-Ghazali", ar: "الإمام الغزالي", ur: "امام غزالی", bn: "ইমাম গাযালী" },
    bio: {
      en: "Abu Hamid al-Ghazali (1058–1111) was a theologian, philosopher and mystic. His Ihya Ulum al-Din remains one of the greatest works in Islamic literature.",
      ar: "أبو حامد الغزالي (450–505 هـ) فيلسوف وعالم ومتصوف",
    },
    era: "Classical",
    birth_date_hijri: "450 AH",
    death_date_hijri: "505 AH",
    photo_url: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const sampleCategories = [
  { id: "c1", slug: "aqeedah", name: { en: "Aqeedah", ar: "عقيدة", ur: "عقیدہ", bn: "আক্বীদাহ" }, description: { en: "Islamic Creed & Theology", ar: "العقيدة الإسلامية" }, sort_order: 1, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c2", slug: "manhaj", name: { en: "Manhaj", ar: "منهج", ur: "منہج", bn: "মানহাজ" }, description: { en: "Methodology of the Salaf", ar: "منهج السلف الصالح" }, sort_order: 2, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c3", slug: "fiqh", name: { en: "Fiqh", ar: "فقه", ur: "فقہ", bn: "ফিকহ" }, description: { en: "Islamic Jurisprudence", ar: "الفقه الإسلامي" }, sort_order: 3, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث", ur: "حدیث", bn: "হাদীস" }, description: { en: "Prophetic Traditions", ar: "الحديث النبوي" }, sort_order: 4, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c5", slug: "tafsir", name: { en: "Tafsir", ar: "تفسير", ur: "تفسیر", bn: "তাফসীর" }, description: { en: "Quranic Exegesis", ar: "تفسير القرآن" }, sort_order: 5, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c6", slug: "seerah", name: { en: "Seerah", ar: "سيرة", ur: "سیرت", bn: "সীরাত" }, description: { en: "Prophetic Biography", ar: "السيرة النبوية" }, sort_order: 6, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c7", slug: "arabic-language", name: { en: "Arabic Language", ar: "اللغة العربية", ur: "عربی زبان", bn: "আরবি ভাষা" }, description: { en: "Grammar, Morphology & Rhetoric", ar: "النحو والصرف والبلاغة" }, sort_order: 7, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c8", slug: "history", name: { en: "History", ar: "تاريخ", ur: "تاریخ", bn: "ইতিহাস" }, description: { en: "Islamic History & Civilisation", ar: "التاريخ الإسلامي" }, sort_order: 8, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c9", slug: "fatawa", name: { en: "Fatawa", ar: "فتاوى", ur: "فتاوی", bn: "ফাতাওয়া" }, description: { en: "Scholarly Rulings & Verdicts", ar: "الفتاوى الشرعية" }, sort_order: 9, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "c10", slug: "tazkiyah", name: { en: "Tazkiyah", ar: "تزكية", ur: "تزکیہ", bn: "তাযকিয়াহ" }, description: { en: "Purification of the Soul", ar: "تزكية النفس" }, sort_order: 10, icon_url: null, parent_id: null, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];

// ── Helper to build an Open Library cover URL from an ISBN ──────────────────
const olCover = (isbn: string, size: "S" | "M" | "L" = "L") =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-${size}.jpg`;

export const sampleBooks = [
  // ────────────────────────── AQEEDAH (c1) ──────────────────────────
  {
    id: "b1",
    title: { en: "Kitab at-Tawheed", ar: "كتاب التوحيد" },
    slug: "kitab-at-tawheed",
    author_id: "a9",
    category_id: "c1",
    language_code: "ar",
    description: { en: "A foundational text on Islamic monotheism explaining the true meaning of Tawheed and its categories. Written by Muhammad ibn Abdul-Wahhab, it is widely studied across the Muslim world.", ar: "كتاب أساسي في التوحيد الإسلامي يشرح معنى التوحيد وأقسامه" },
    pdf_url: "",
    cover_image_url: olCover("9960740056"),
    page_count: 320,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 15420,
    download_count: 8930,
    published_at: "2024-01-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a9", name: { en: "Muhammad ibn Abdul-Wahhab", ar: "محمد بن عبد الوهاب" } },
    category: { id: "c1", slug: "aqeedah", name: { en: "Aqeedah", ar: "عقيدة" } },
  },
  {
    id: "b2",
    title: { en: "Al-Aqeedah Al-Wasitiyyah", ar: "العقيدة الواسطية" },
    slug: "al-aqeedah-al-wasitiyyah",
    author_id: "a1",
    category_id: "c1",
    language_code: "ar",
    description: { en: "A classic text on the creed of Ahl as-Sunnah wal-Jama'ah, covering the names and attributes of Allah. It is one of Ibn Taymiyyah's most studied works.", ar: "رسالة في عقيدة أهل السنة والجماعة" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 96,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 12800,
    download_count: 6540,
    published_at: "2024-01-20T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a1", name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
    category: { id: "c1", slug: "aqeedah", name: { en: "Aqeedah", ar: "عقيدة" } },
  },
  {
    id: "b11",
    title: { en: "The Three Fundamental Principles", ar: "الأصول الثلاثة" },
    slug: "three-fundamental-principles",
    author_id: "a5",
    category_id: "c1",
    language_code: "ar",
    description: { en: "An explanation of the three questions asked in the grave: Who is your Lord, your religion, and your Prophet? A must-read for every Muslim.", ar: "شرح ثلاثة الأصول" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 80,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 8900,
    download_count: 5600,
    published_at: "2024-05-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a5", name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" } },
    category: { id: "c1", slug: "aqeedah", name: { en: "Aqeedah", ar: "عقيدة" } },
  },
  {
    id: "b15",
    title: { en: "Sharh al-Aqeedah at-Tahawiyyah", ar: "شرح العقيدة الطحاوية" },
    slug: "sharh-al-aqeedah-at-tahawiyyah",
    author_id: "a2",
    category_id: "c1",
    language_code: "ar",
    description: { en: "Commentary on the creed of Imam at-Tahawi, a widely studied text on orthodox Sunni beliefs covering the fundamentals of Islamic theology.", ar: "شرح العقيدة الطحاوية" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 540,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 6100,
    download_count: 3200,
    published_at: "2024-07-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a2", name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
    category: { id: "c1", slug: "aqeedah", name: { en: "Aqeedah", ar: "عقيدة" } },
  },

  // ────────────────────────── MANHAJ (c2) ──────────────────────────
  {
    id: "b16",
    title: { en: "Talbis Iblis", ar: "تلبيس إبليس" },
    slug: "talbis-iblis",
    author_id: "a2",
    category_id: "c2",
    language_code: "ar",
    description: { en: "Devil's Deceptions — an exposition of the tricks and schemes of Shaytan upon the children of Adam, refuting deviant sects and innovations.", ar: "تلبيس إبليس" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 380,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 4200,
    download_count: 2100,
    published_at: "2024-07-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a2", name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
    category: { id: "c2", slug: "manhaj", name: { en: "Manhaj", ar: "منهج" } },
  },
  {
    id: "b17",
    title: { en: "Iqtida as-Sirat al-Mustaqim", ar: "اقتضاء الصراط المستقيم" },
    slug: "iqtida-as-sirat-al-mustaqim",
    author_id: "a1",
    category_id: "c2",
    language_code: "ar",
    description: { en: "The Requirements of the Straight Path — Ibn Taymiyyah warns against imitating non-Muslims in customs and worship, calling Muslims back to the pure Sunnah.", ar: "اقتضاء الصراط المستقيم لمخالفة أصحاب الجحيم" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 340,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 3800,
    download_count: 1900,
    published_at: "2024-08-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a1", name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
    category: { id: "c2", slug: "manhaj", name: { en: "Manhaj", ar: "منهج" } },
  },
  {
    id: "b28",
    title: { en: "Usool as-Sunnah", ar: "أصول السنة" },
    slug: "usool-as-sunnah",
    author_id: "a4",
    category_id: "c2",
    language_code: "ar",
    description: { en: "Foundations of the Sunnah — a concise treatise explaining the fundamental principles of Ahl as-Sunnah wal-Jama'ah regarding creed and methodology.", ar: "أصول السنة للإمام أحمد بن حنبل" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 60,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 3100,
    download_count: 1700,
    published_at: "2024-09-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a4", name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" } },
    category: { id: "c2", slug: "manhaj", name: { en: "Manhaj", ar: "منهج" } },
  },

  // ────────────────────────── FIQH (c3) ──────────────────────────
  {
    id: "b12",
    title: { en: "Bulugh al-Maram", ar: "بلوغ المرام" },
    slug: "bulugh-al-maram",
    author_id: "a11",
    category_id: "c3",
    language_code: "ar",
    description: { en: "A collection of hadith pertaining to Islamic jurisprudence compiled by Ibn Hajar al-Asqalani. It is widely used as a primary reference for deriving fiqh rulings.", ar: "بلوغ المرام من أدلة الأحكام" },
    pdf_url: "",
    cover_image_url: olCover("9786035000826"),
    page_count: 450,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 6700,
    download_count: 3400,
    published_at: "2024-05-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a11", name: { en: "Ibn Hajar al-Asqalani", ar: "ابن حجر العسقلاني" } },
    category: { id: "c3", slug: "fiqh", name: { en: "Fiqh", ar: "فقه" } },
  },
  {
    id: "b18",
    title: { en: "Al-Sharh al-Mumti'", ar: "الشرح الممتع" },
    slug: "al-sharh-al-mumti",
    author_id: "a5",
    category_id: "c3",
    language_code: "ar",
    description: { en: "The Enjoyable Explanation — Shaykh al-Uthaymeen's comprehensive commentary on Zad al-Mustaqni', covering Hanbali fiqh in detail.", ar: "الشرح الممتع على زاد المستقنع" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 3600,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 7800,
    download_count: 4200,
    published_at: "2024-08-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a5", name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" } },
    category: { id: "c3", slug: "fiqh", name: { en: "Fiqh", ar: "فقه" } },
  },
  {
    id: "b29",
    title: { en: "Minhaj at-Talibin", ar: "منهاج الطالبين" },
    slug: "minhaj-at-talibin",
    author_id: "a3",
    category_id: "c3",
    language_code: "ar",
    description: { en: "The Way of the Seekers — Imam an-Nawawi's authoritative work on Shafi'i fiqh, covering worship, transactions, marriage, and more.", ar: "منهاج الطالبين وعمدة المفتين" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 520,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 5400,
    download_count: 2800,
    published_at: "2024-09-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a3", name: { en: "Imam an-Nawawi", ar: "الإمام النووي" } },
    category: { id: "c3", slug: "fiqh", name: { en: "Fiqh", ar: "فقه" } },
  },

  // ────────────────────────── HADITH (c4) ──────────────────────────
  {
    id: "b4",
    title: { en: "Riyad as-Salihin", ar: "رياض الصالحين" },
    slug: "riyad-as-salihin",
    author_id: "a3",
    category_id: "c4",
    language_code: "ar",
    description: { en: "Gardens of the Righteous — a compilation of hadith covering all aspects of a Muslim's daily life, from worship to manners to governance.", ar: "رياض الصالحين من كلام سيد المرسلين" },
    pdf_url: "",
    cover_image_url: olCover("9781590080160"),
    page_count: 680,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 22500,
    download_count: 14300,
    published_at: "2024-02-10T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a3", name: { en: "Imam an-Nawawi", ar: "الإمام النووي" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },
  {
    id: "b5",
    title: { en: "Al-Arba'in An-Nawawiyyah", ar: "الأربعين النووية" },
    slug: "al-arbain-an-nawawiyyah",
    author_id: "a3",
    category_id: "c4",
    language_code: "ar",
    description: { en: "The Forty Hadith of Imam Nawawi — a concise collection of 42 fundamental prophetic traditions that form the core of Islamic teachings.", ar: "الأربعون حديثاً النووية" },
    pdf_url: "",
    cover_image_url: olCover("9780946621651"),
    page_count: 120,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 31200,
    download_count: 19800,
    published_at: "2024-02-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a3", name: { en: "Imam an-Nawawi", ar: "الإمام النووي" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },
  {
    id: "b7",
    title: { en: "Sahih al-Bukhari", ar: "صحيح البخاري" },
    slug: "sahih-al-bukhari",
    author_id: "a8",
    category_id: "c4",
    language_code: "ar",
    description: { en: "The most authentic collection of hadith, compiled by Imam al-Bukhari over 16 years from over 600,000 narrations. It contains 7,563 hadith.", ar: "الجامع المسند الصحيح المختصر من أمور رسول الله ﷺ وسننه وأيامه" },
    pdf_url: "",
    cover_image_url: olCover("9781567445190"),
    page_count: 2600,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 45200,
    download_count: 29400,
    published_at: "2024-03-10T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a8", name: { en: "Imam al-Bukhari", ar: "الإمام البخاري" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },
  {
    id: "b10",
    title: { en: "Fath al-Bari", ar: "فتح الباري" },
    slug: "fath-al-bari",
    author_id: "a11",
    category_id: "c4",
    language_code: "ar",
    description: { en: "The most celebrated commentary on Sahih al-Bukhari, authored by Ibn Hajar al-Asqalani. It took him 25 years to complete.", ar: "فتح الباري شرح صحيح البخاري" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 4800,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 11300,
    download_count: 6800,
    published_at: "2024-04-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a11", name: { en: "Ibn Hajar al-Asqalani", ar: "ابن حجر العسقلاني" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },
  {
    id: "b13",
    title: { en: "Silsilat al-Ahadith as-Sahihah", ar: "سلسلة الأحاديث الصحيحة" },
    slug: "silsilat-al-ahadith-as-sahihah",
    author_id: "a6",
    category_id: "c4",
    language_code: "ar",
    description: { en: "Series of Authentic Hadith — a multi-volume verification and compilation of authentic hadith by the master of modern hadith science.", ar: "سلسلة الأحاديث الصحيحة وشيء من فقهها وفوائدها" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 2100,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 5400,
    download_count: 2900,
    published_at: "2024-06-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a6", name: { en: "Shaykh al-Albani", ar: "الشيخ الألباني" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },
  {
    id: "b19",
    title: { en: "Sahih Muslim", ar: "صحيح مسلم" },
    slug: "sahih-muslim",
    author_id: "a10",
    category_id: "c4",
    language_code: "ar",
    description: { en: "The second most authentic hadith collection after Sahih al-Bukhari, compiled by Imam Muslim. It is known for its strict methodology.", ar: "المسند الصحيح المختصر بنقل العدل عن العدل إلى رسول الله ﷺ" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 2200,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 38400,
    download_count: 24100,
    published_at: "2024-09-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a10", name: { en: "Imam Muslim", ar: "الإمام مسلم" } },
    category: { id: "c4", slug: "hadith", name: { en: "Hadith", ar: "حديث" } },
  },

  // ────────────────────────── TAFSIR (c5) ──────────────────────────
  {
    id: "b6",
    title: { en: "Tafsir Ibn Kathir", ar: "تفسير ابن كثير" },
    slug: "tafsir-ibn-kathir",
    author_id: "a7",
    category_id: "c5",
    language_code: "ar",
    description: { en: "One of the most respected tafsirs of the Quran, known for interpreting the Quran using hadith and statements of the Sahabah.", ar: "تفسير القرآن العظيم" },
    pdf_url: "",
    cover_image_url: olCover("9789960892740"),
    page_count: 3200,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 28700,
    download_count: 16500,
    published_at: "2024-03-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a7", name: { en: "Ibn Kathir", ar: "ابن كثير" } },
    category: { id: "c5", slug: "tafsir", name: { en: "Tafsir", ar: "تفسير" } },
  },
  {
    id: "b20",
    title: { en: "Tafsir as-Sa'di", ar: "تفسير السعدي" },
    slug: "tafsir-as-sadi",
    author_id: "a5",
    category_id: "c5",
    language_code: "ar",
    description: { en: "Taysir al-Karim ar-Rahman — A clear and accessible Quranic commentary by Shaykh Abdur-Rahman as-Sa'di, widely recommended for students of knowledge.", ar: "تيسير الكريم الرحمن في تفسير كلام المنان" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 1400,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 9200,
    download_count: 5100,
    published_at: "2024-09-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a5", name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" } },
    category: { id: "c5", slug: "tafsir", name: { en: "Tafsir", ar: "تفسير" } },
  },
  {
    id: "b30",
    title: { en: "Tafsir al-Jalalayn", ar: "تفسير الجلالين" },
    slug: "tafsir-al-jalalayn",
    author_id: "a3",
    category_id: "c5",
    language_code: "ar",
    description: { en: "A concise and popular tafsir co-authored by Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti. Known for its brevity and clarity.", ar: "تفسير الجلالين — تفسير مختصر للقرآن الكريم" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 800,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 7300,
    download_count: 3900,
    published_at: "2024-10-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a3", name: { en: "Imam an-Nawawi", ar: "الإمام النووي" } },
    category: { id: "c5", slug: "tafsir", name: { en: "Tafsir", ar: "تفسير" } },
  },

  // ────────────────────────── SEERAH (c6) ──────────────────────────
  {
    id: "b3",
    title: { en: "Zad al-Ma'ad", ar: "زاد المعاد" },
    slug: "zad-al-maad",
    author_id: "a2",
    category_id: "c6",
    language_code: "ar",
    description: { en: "Provisions of the Hereafter — a comprehensive guide to the Prophet's ﷺ life, practices, jurisprudence, and daily routines.", ar: "زاد المعاد في هدي خير العباد" },
    pdf_url: "",
    cover_image_url: olCover("9781891229237"),
    page_count: 1200,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 18900,
    download_count: 11200,
    published_at: "2024-02-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a2", name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
    category: { id: "c6", slug: "seerah", name: { en: "Seerah", ar: "سيرة" } },
  },
  {
    id: "b21",
    title: { en: "Ar-Raheeq al-Makhtum (The Sealed Nectar)", ar: "الرحيق المختوم" },
    slug: "ar-raheeq-al-makhtum",
    author_id: "a4",
    category_id: "c6",
    language_code: "ar",
    description: { en: "The Sealed Nectar — an award-winning biography of Prophet Muhammad ﷺ by Safi-ur-Rahman Mubarakpuri. Winner of the first prize in a worldwide competition.", ar: "الرحيق المختوم — سيرة نبوية" },
    pdf_url: "",
    cover_image_url: olCover("9781591440710"),
    page_count: 480,
    is_downloadable: true,
    is_featured: true,
    copyright: "public_domain" as const,
    view_count: 35600,
    download_count: 22800,
    published_at: "2024-10-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a4", name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" } },
    category: { id: "c6", slug: "seerah", name: { en: "Seerah", ar: "سيرة" } },
  },
  {
    id: "b31",
    title: { en: "As-Seerah An-Nabawiyyah", ar: "السيرة النبوية" },
    slug: "as-seerah-an-nabawiyyah",
    author_id: "a7",
    category_id: "c6",
    language_code: "ar",
    description: { en: "The Prophetic Biography as narrated by Ibn Kathir — drawn from his larger work Al-Bidayah wan-Nihayah, focusing on the life of the Prophet ﷺ.", ar: "السيرة النبوية لابن كثير" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 960,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 6800,
    download_count: 3600,
    published_at: "2024-10-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a7", name: { en: "Ibn Kathir", ar: "ابن كثير" } },
    category: { id: "c6", slug: "seerah", name: { en: "Seerah", ar: "سيرة" } },
  },

  // ────────────────────────── ARABIC LANGUAGE (c7) ──────────────────────────
  {
    id: "b22",
    title: { en: "Al-Ajrumiyyah", ar: "الآجرومية" },
    slug: "al-ajrumiyyah",
    author_id: "a5",
    category_id: "c7",
    language_code: "ar",
    description: { en: "A classical primer on Arabic grammar by Ibn Ajurrum, widely used as the first textbook for students of Arabic grammar worldwide.", ar: "المقدمة الآجرومية في مبادئ علم العربية" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 40,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 12400,
    download_count: 8100,
    published_at: "2024-10-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a5", name: { en: "Shaykh al-Uthaymeen", ar: "الشيخ العثيمين" } },
    category: { id: "c7", slug: "arabic-language", name: { en: "Arabic Language", ar: "اللغة العربية" } },
  },
  {
    id: "b23",
    title: { en: "Qatr an-Nada", ar: "قطر الندى" },
    slug: "qatr-an-nada",
    author_id: "a1",
    category_id: "c7",
    language_code: "ar",
    description: { en: "Drops of Dew — an intermediate Arabic grammar text by Ibn Hisham, covering syntax (nahw) in a clear and structured manner.", ar: "قطر الندى وبل الصدى — في النحو العربي" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 180,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 5600,
    download_count: 3200,
    published_at: "2024-11-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a1", name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
    category: { id: "c7", slug: "arabic-language", name: { en: "Arabic Language", ar: "اللغة العربية" } },
  },
  {
    id: "b32",
    title: { en: "Alfiyyat Ibn Malik", ar: "ألفية ابن مالك" },
    slug: "alfiyyat-ibn-malik",
    author_id: "a3",
    category_id: "c7",
    language_code: "ar",
    description: { en: "The Thousand-Line Poem of Ibn Malik — the most famous didactic poem on Arabic grammar, memorized by students of Arabic worldwide for centuries.", ar: "ألفية ابن مالك في النحو والصرف" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 120,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 8900,
    download_count: 5400,
    published_at: "2024-11-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a3", name: { en: "Imam an-Nawawi", ar: "الإمام النووي" } },
    category: { id: "c7", slug: "arabic-language", name: { en: "Arabic Language", ar: "اللغة العربية" } },
  },

  // ────────────────────────── HISTORY (c8) ──────────────────────────
  {
    id: "b14",
    title: { en: "Al-Bidayah wan-Nihayah", ar: "البداية والنهاية" },
    slug: "al-bidayah-wan-nihayah",
    author_id: "a7",
    category_id: "c8",
    language_code: "ar",
    description: { en: "The Beginning and The End — a monumental universal history from the creation of the world through the events of the author's time, by Ibn Kathir.", ar: "البداية والنهاية في التاريخ" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 4200,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 8200,
    download_count: 4700,
    published_at: "2024-06-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a7", name: { en: "Ibn Kathir", ar: "ابن كثير" } },
    category: { id: "c8", slug: "history", name: { en: "History", ar: "تاريخ" } },
  },
  {
    id: "b24",
    title: { en: "Stories of the Prophets", ar: "قصص الأنبياء" },
    slug: "stories-of-the-prophets",
    author_id: "a7",
    category_id: "c8",
    language_code: "ar",
    description: { en: "Qisas al-Anbiya — a collection of stories of the Prophets mentioned in the Quran, narrated by Ibn Kathir with hadith references.", ar: "قصص الأنبياء لابن كثير" },
    pdf_url: "",
    cover_image_url: olCover("9781591440116"),
    page_count: 460,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 14600,
    download_count: 9200,
    published_at: "2024-11-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a7", name: { en: "Ibn Kathir", ar: "ابن كثير" } },
    category: { id: "c8", slug: "history", name: { en: "History", ar: "تاريخ" } },
  },
  {
    id: "b33",
    title: { en: "Tarikh at-Tabari", ar: "تاريخ الطبري" },
    slug: "tarikh-at-tabari",
    author_id: "a8",
    category_id: "c8",
    language_code: "ar",
    description: { en: "The History of the Prophets and Kings — one of the most comprehensive chronicles of Islamic and pre-Islamic history by Imam at-Tabari.", ar: "تاريخ الرسل والملوك — تاريخ الطبري" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 5600,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 4800,
    download_count: 2500,
    published_at: "2024-12-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a8", name: { en: "Imam al-Bukhari", ar: "الإمام البخاري" } },
    category: { id: "c8", slug: "history", name: { en: "History", ar: "تاريخ" } },
  },

  // ────────────────────────── FATAWA (c9) ──────────────────────────
  {
    id: "b8",
    title: { en: "Majmu' al-Fatawa", ar: "مجموع الفتاوى" },
    slug: "majmu-al-fatawa",
    author_id: "a1",
    category_id: "c9",
    language_code: "ar",
    description: { en: "A comprehensive 37-volume collection of religious rulings and answers by Shaykh al-Islam Ibn Taymiyyah, covering creed, worship, and more.", ar: "مجموع فتاوى شيخ الإسلام ابن تيمية" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 5400,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 9800,
    download_count: 5200,
    published_at: "2024-03-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a1", name: { en: "Ibn Taymiyyah", ar: "ابن تيمية" } },
    category: { id: "c9", slug: "fatawa", name: { en: "Fatawa", ar: "فتاوى" } },
  },
  {
    id: "b25",
    title: { en: "Fatawa Ibn Baz", ar: "فتاوى ابن باز" },
    slug: "fatawa-ibn-baz",
    author_id: "a4",
    category_id: "c9",
    language_code: "ar",
    description: { en: "A multi-volume compilation of fatawa (religious rulings) by Shaykh Ibn Baz on topics of creed, worship, transactions, and contemporary issues.", ar: "مجموع فتاوى ومقالات الشيخ ابن باز" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 4200,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 7300,
    download_count: 4100,
    published_at: "2024-11-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a4", name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" } },
    category: { id: "c9", slug: "fatawa", name: { en: "Fatawa", ar: "فتاوى" } },
  },
  {
    id: "b34",
    title: { en: "Fatawa al-Lajnah ad-Da'imah", ar: "فتاوى اللجنة الدائمة" },
    slug: "fatawa-al-lajnah",
    author_id: "a4",
    category_id: "c9",
    language_code: "ar",
    description: { en: "A compilation of fatawa issued by the Permanent Committee for Scholarly Research and Ifta of Saudi Arabia, covering all aspects of Islamic life.", ar: "فتاوى اللجنة الدائمة للبحوث العلمية والإفتاء" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 3200,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 5200,
    download_count: 2800,
    published_at: "2024-12-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a4", name: { en: "Shaykh Ibn Baz", ar: "الشيخ ابن باز" } },
    category: { id: "c9", slug: "fatawa", name: { en: "Fatawa", ar: "فتاوى" } },
  },

  // ────────────────────────── TAZKIYAH (c10) ──────────────────────────
  {
    id: "b9",
    title: { en: "Madarij as-Salikin", ar: "مدارج السالكين" },
    slug: "madarij-as-salikin",
    author_id: "a2",
    category_id: "c10",
    language_code: "ar",
    description: { en: "Stations of the Seekers — an in-depth exploration of the spiritual stations on the path to Allah, based on the work of al-Harawi.", ar: "مدارج السالكين بين منازل إياك نعبد وإياك نستعين" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 900,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 7600,
    download_count: 4100,
    published_at: "2024-04-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a2", name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
    category: { id: "c10", slug: "tazkiyah", name: { en: "Tazkiyah", ar: "تزكية" } },
  },
  {
    id: "b26",
    title: { en: "Al-Jawab al-Kafi", ar: "الجواب الكافي" },
    slug: "al-jawab-al-kafi",
    author_id: "a2",
    category_id: "c10",
    language_code: "ar",
    description: { en: "The Sufficient Answer — Ibn al-Qayyim answers a question about the cure for sins and disobedience, with deep insights into the heart's ailments and their remedies.", ar: "الجواب الكافي لمن سأل عن الدواء الشافي — الداء والدواء" },
    pdf_url: "",
    cover_image_url: null,
    page_count: 320,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 6800,
    download_count: 3700,
    published_at: "2024-12-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a2", name: { en: "Ibn al-Qayyim", ar: "ابن القيم" } },
    category: { id: "c10", slug: "tazkiyah", name: { en: "Tazkiyah", ar: "تزكية" } },
  },
  {
    id: "b27",
    title: { en: "Ihya Ulum al-Din", ar: "إحياء علوم الدين" },
    slug: "ihya-ulum-al-din",
    author_id: "a12",
    category_id: "c10",
    language_code: "ar",
    description: { en: "Revival of the Religious Sciences — Imam al-Ghazali's magnum opus covering worship, daily life, vices, and virtues in extraordinary depth.", ar: "إحياء علوم الدين — كتاب الإمام الغزالي" },
    pdf_url: "",
    cover_image_url: olCover("9781941610213"),
    page_count: 4400,
    is_downloadable: true,
    is_featured: false,
    copyright: "public_domain" as const,
    view_count: 11200,
    download_count: 6300,
    published_at: "2024-12-15T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    author: { id: "a12", name: { en: "Imam al-Ghazali", ar: "الإمام الغزالي" } },
    category: { id: "c10", slug: "tazkiyah", name: { en: "Tazkiyah", ar: "تزكية" } },
  },
];

/** Get featured sample books only */
export function getSampleFeaturedBooks() {
  return sampleBooks.filter((b) => b.is_featured);
}

/** Filter sample books by category slug */
export function getSampleBooksByCategory(categorySlug: string) {
  return sampleBooks.filter((b) => b.category?.slug === categorySlug);
}

/** Filter sample books by search query */
export function searchSampleBooks(query: string) {
  const q = query.toLowerCase();
  return sampleBooks.filter(
    (b) =>
      b.title.en?.toLowerCase().includes(q) ||
      b.title.ar?.includes(q) ||
      b.author?.name?.en?.toLowerCase().includes(q) ||
      b.author?.name?.ar?.includes(q) ||
      b.description?.en?.toLowerCase().includes(q),
  );
}
